name: Build and Deploy to Cloud Run

on:
    push:
        branches:
            - master

env:
    GCP_PROJECT_ID: ${{ secrets.PROJECT_ID }}
    GCP_SA_EMAIL: ${{ secrets.SA_EMAIL }}
    GCP_SA_KEY: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS}}
    GCP_RUN_REGION: europe-north1
    GCP_SERVICE_NAME: finch_backend

jobs:
  build:
    name: Cloud Run Deployment
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@master
        with:
          version: 'latest'
          service_account_email: $GCP_SA_EMAIL
          service_account_key: $GCP_SA_KEY
          export_default_credentials: true

      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      - name: Build
        run: |
          docker build --build-arg JAR_FILE=build/libs/\*.jar -t gcr.io/$GCP_PROJECT_ID/$GCP_SERVICE_NAME:latest .

      - name: Push
        run: |
          docker push gcr.io/$GCP_PROJECT_ID/$GCP_SERVICE_NAME:latest

      - name: Deploy
        run: |
          gcloud run deploy $GCP_SERVICE_NAME \
          --region $GCP_RUN_REGION \
          --image gcr.io/$GCP_PROJECT_ID/@GCP_SERVICE_NAME \
          --platform managed \
          --allow-unauthenticated \
          --project $GCP_PROJECT_ID
