name: Build and Deploy to Cloud Run

on:
    push:
        branches:
            - master

env:
    GCP_PROJECT_ID: ${{ secrets.PROJECT_ID }}
    GCP_RUN_REGION: europe-north1
    GCP_SERVICE_NAME: finch-backend
    JWT_SECRET: ${{ secrets.JWT_SECRET }}
    DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
    DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
    DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
    DATABASE_INSTANCE_CONNECTION_NAME: ${{ secrets.DATABASE_INSTANCE_CONNECTION_NAME }}
    GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

jobs:
  build:
    name: Cloud Run Deployment
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@master
        with:
          version: 'latest'
          service_account_key: $GOOGLE_APPLICATION_CREDENTIALS
          # service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS}}

      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      - name: Build
        run: |
          docker build -t gcr.io/$GCP_PROJECT_ID/$GCP_SERVICE_NAME:latest .

      - name: Push
        run: |
          docker push gcr.io/$GCP_PROJECT_ID/$GCP_SERVICE_NAME:latest

      - name: Deploy
        run: |
          gcloud run deploy $GCP_SERVICE_NAME \
          --region $GCP_RUN_REGION \
          --image gcr.io/$GCP_PROJECT_ID/$GCP_SERVICE_NAME \
          --platform managed \
          --allow-unauthenticated \
          --project $GCP_PROJECT_ID \
          --set-env-vars JWT_SECRET=$JWT_SECRET \
          --set-env-vars DATABASE_NAME=$DATABASE_NAME \
          --set-env-vars DATABASE_USERNAME=$DATABASE_USERNAME \
          --set-env-vars DATABASE_PASSWORD=$DATABASE_PASSWORD \
          --set-env-vars DATABASE_INSTANCE_CONNECTION_NAME=$DATABASE_INSTANCE_CONNECTION_NAME \
          --set-env-vars DATABASE_INSTANCE_CONNECTION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS
